### ISSUE TITLE
The Mystery of Livonias vanished buildings...

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1001]
Once upon a time some people were playing Antistasi Livonia on our second server.
They were minding their business, doing the usual things.
Killing traitors, helping refugees, taking out patrols and roadblocks - the ususal thing, ya know.
Suddenly they got shot!
They didn't see or hear the enemies coming!
Then they saw it!
Bullets coming from a building which seemed to be intact. But how could that be?!?

Issue:
AI shooting through buildings on Livonia

Possible causes prooven:
- Antistasi not being able to process enoch data
--> Ruled out because it's not reproducable on local
- HCs not having access to enoch asset data
--> Ruled out by testing on the server

Possible cause remaining:
- After a restart Antistasi is not able to create ruins for certain assets, therefore the server does not take the buildings into consideration as neither ruined nor complete buildings are being placed but clients still see the buildings as they are for some reason visible for them?!?

Possible trace:
```
13:51:14 "Loading Destroyed Buildings: Unable to create ruin for Land_Cargo_Patrol_V2_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_Barracks_06_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_Shed_Small_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_Cargo_Patrol_V2_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_Cargo_Patrol_V2_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_spp_Transformer_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_Workshop_02_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_Shed_09_F"
13:51:15 "Loading Destroyed Buildings: Unable to create ruin for Land_House_1W02_F"
```

For more information please look at rpt arma3server_x64_2020-05-02_18-34-41 provided in the corresponding discord channel.

**Comment by jaj22** [comment]
Ok, so I found two issues related to loading destroyed buildings:

1. nearestObject is retarded and sometimes picks another nearby building.
2. destroyedBuildings is being loaded twice, so every building will log "unable to create ruin" at least once.

However, neither of these can cause the specified symptoms (other than the RPT spam), because there's no desync: At worst, it fails to destroy the correct buildings on load. Every client should still see the same buildings.

Otherwise I have a couple of weirder ideas but more input would help, as it's unlikely that I can replicate the desync problem on the current information:

1. Is there ever a desync problem with buildings destroyed since the last restart?
2. Do all human players always see the same thing?
