### ISSUE TITLE
[Change Request]: Undercover Exploiting (Outposts)

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1025]
So as Mezcal allready reported aswell with his weird way of Pushing a Box out of an Outpost, we should also Apply losing Undercover for Outposts.

Flying in and Slingloading would also work on Current Unstable which we have an Issue for aswell.

~~since you currently can just drive in Load the box with JNL and fuck off.~~ Older Version on server Ignore that.

-------> Apply the Same Detection as Airbases have for Outposts since they are intended as Military Areas ofcourse.

**Comment by jaj22** [comment]
Loading the box with JNL was fixed in #974.

The other issues (outpost != airbases, one-shot area checks) were apparently written that way intentionally and so would need discussion to change. My view is that the area checks should be periodic rather than one-shot, so elaborate & slow schemes like pushing the ammo crate with a vehicle would become relatively dangerous.

**Comment by MeltedPixel** [comment]
Closing as per @Bob-Murphy. Confirmed fixed.
