### ISSUE TITLE
AI mod Blacklist

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#125]
a suggestion has stated that the mission has a blacklist for AI changing mods including one that has no effect without having its components placed on the map.

this blacklist kicks you off the mission when it detects "incompatible" mods

non-effecting mod is ALIVE btw

**Comment by Bob-Murphy** [comment]
Could you get the steam workshop ID from that mod? maybe they use this to block it

**Comment by Toakan** [comment]
There is a check specifically for it here : https://github.com/official-antistasi-community/A3-Antistasi-1.4/blob/master/A3-Antistasi/modBlacklist.sqf

**Comment by Bob-Murphy** [comment]
It needs to be evaluated why the mods were blacklisted and if there are compatibility problems.
We will deal with this one in the future.

**Comment by PoweredByPot** [comment]
just my two cents, if we COULD get this to work (read tolerate) ALiVE I would be the happiest kid in the candy store. For years before I ever knew Antistasi existed I tried to build something similar using ALiVE as a base. There are a TON of things we could do that would add some flavor to Antistasi using ALiVE provided performance doesn't nosedive.

That being said I do find it very very likely that absolutely everything would explode in a massive fireball if we try and make the two work together. I've also never had the chance to actually try, because barbolani.

**Comment by Bob-Murphy** [comment]
Do you mean explode in a good way because it's an awesome mod?

Also, I would rather postpone it further back than 2.02.
After 2.01 I would like to port Antistasi to other maps first, as this would bring a shitton of new possibilities for the Antistasi community.

**Comment by PoweredByPot** [comment]
I would not consider this urgent in the least bit. Simply allowing it to not boot us out would be great.

The testing process for getting working ALiVE features into Antistasi though I think will take weeks. Totally agree not with our current time.

**Comment by Toakan** [comment]
@PoweredByPot This isn't issue isn't about integrating ALiVE, it's simply to remove the line of code which closes the mission if ALiVE is detected.

We also requires checking to see why ALiVE was blacklisted in the first place. Again, not integrating the mod, just making sure it doesn't do funky things _if_ loaded.

**Comment by Bob-Murphy** [comment]
This needs to be looked at when AI is changed.
Please don't start working on it.

**Comment by MeltedPixel** [comment]
This isn't something we should be doing after extensive testing on how Antistasi and out AI management influences them.
