### ISSUE TITLE
Some wrong classnames in the 3CB templates

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1275]
*Version:* Unstable

*Mods:* 3CB

*Environment*: Any

***Issue:***
I cleared up the vanilla templates (terrible) and RHS (pretty good), but I'm leaving 3CB for someone who knows what they're doing with it. List of missing classnames below:

```
3CB Tropical:
[""UK3CB_CCM_I_Hilux_Spg"",""UK3CB_BAF_L111A1"",""UK3CB_BAF_L16"",""UK3CB_BAF_Tripod"",""UK3CB_BAF_L16_Tripod""]

3CB Temperate:
[""UK3CB_CCM_I_Hilux_Spg"",""UK3CB_BAF_L111A1"",""UK3CB_BAF_L16"",""UK3CB_BAF_Tripod"",""UK3CB_BAF_L16_Tripod""]

3CB Arid:
[""UK3CB_CCM_I_Hilux_Spg"",""UK3CB_BAF_SL_DDPM"",""UK3CB_BAF_L111A1"",""UK3CB_BAF_L16"",""UK3CB_BAF_Tripod"",""UK3CB_BAF_L16_Tripod""]

3CB blufor:
[""UK3CB_TKP_I_IFF"",""UUK3CB_TKP_I_CIB_RIF_2"",""UK3CB_TKP_I_Hilux_Ipen"",""RHS_Podnos_Tripod_Bag""]
```

**Comment by Lazejun** [comment]
Going down the List with Possible replacements for the Woopsies:
**"UK3CB_CCM_I_Hilux_Spg"** In Rebell Templates: vehSDKAT = "UK3CB_CCM_I_Hilux_Spg"; -------> Doesent exist.
AT Cars 3CB offers:

0 AT Cars for CCM

3 AT Cars for UN ["UK3CB_UN_I_Hilux_Spg9","UK3CB_UN_I_LR_SPG9","UK3CB_UN_I_UAZ_SPG9"]

3 AT Cars for TKM ["UK3CB_TKM_I_Hilux_Spg9","UK3CB_TKM_I_LR_SPG9","UK3CB_TKM_I_UAZ_SPG9"]

3 AT Cars for FIA (Vanilla Rebells) ["UK3CB_I_G_Hilux_Spg9","UK3CB_I_G_LandRover_SPG9","UK3CB_I_G_UAZ_SPG9"]

![20200715215355_1](https://user-images.githubusercontent.com/57111907/87589589-bbdf3780-c6e5-11ea-83b4-ef653674e0d2.jpg)

---------> Default crew of Vehicles WILL be used which is atleast ONLY their Uniform the **LEAST** harm would be the FIA variant due to Rebell Uniforms.



**"UK3CB_BAF_L111A1"** in ALL BAF Templates: MGStaticNATOB = "UK3CB_BAF_L111A1";

The Classname is correct but it might scream due to being a "Launcher" cause its the same System as **Ace_CSW Statics**

**"UK3CB_BAF_L16"** -------> The same Issue

**"UK3CB_BAF_Tripod"** ----> Same

Since it doesent like assigning a "Launcher" and it would prefer a Backpacks we could go RHS M2 and M252.



**"RHS_Podnos_Tripod_Bag"** in TKA Template: supportStaticNATOB3 = "RHS_Podnos_Tripod_Bag";
-----------> Typo **"RHS_Podnos_Bipod_Bag"**



**"UK3CB_BAF_SL_DDPM"** in BAF_Arid NATOOfficer = "UK3CB_BAF_SC_DDPM";

-----------> Could be assumed as a Typo since Section Leader could be mistaken as "SL" **"UK3CB_BAF_SC_DDPM"**
But: All other Templates use "UK3CB_BAF_Officer_DDPM" as Officer and "UK3CB_BAF_FAC_DDPM" as Officer2 so Traitor.

"UUK3CB_TKP_I_CIB_RIF_2" Typo  ---------> "UK3CB_TKP_I_CIB_RIF_2"
"UK3CB_TKP_I_Hilux_Ipen" Typo -----------> "UK3CB_TKP_I_Hilux_Open"

**Comment by jaj22** [comment]
Ok, looks like the NATO/CSAT backpack vars aren't used in the current code. Instead, it assumes that whatever backpack those units have is where the static weapon comes from. Ideally we'd implement CSWs properly but now is not that time, given that the related code is crazy spaghetti. I'll remove those vars from the sanity check anyway.

UK3CB_TKP_I_OFF only has a handgun so I'll probably just throw in an I_TL to go with the marksman.

I should fix rebel HC vehicles using the stock crew, but I guess the FIA Hilux will do for now.
