### ISSUE TITLE
QRFs use bad map marker

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1299]
Sometimes, when convoys spawn, an error popup shows saying that there is no entry in "bin/config.bin/CfgMarkers._motor_inf".
This marker needs correcting or replacing.

**Comment by jaj22** [comment]
What happens is that the convoy crew is technically civilian for the money & supplies convoys due to using stock Arma crew spawning functions. vehicleMarkers doesn't have a case for civilian vehicles, so it bugs out.

At some point we should have our own vehicle/crew spawning functions to prevent bad-faction crew issues, but not before 2.3. I'll hack-fix vehicleMarkers for now.
