### ISSUE TITLE
FF events may be preceded by events that contain incorrect Info

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1351]
**Describe the bug**
vanilla rpg-7 was fired directly upon friendlies, no FF warning, still warning from fragmentation from nearby explosion sometimes. in addition ocean gulag has been reported of damaging and or knocking people unconscious.

**To Reproduce**
for the prg-7, get a rpg-7 shoot directly on a friendly.

**Expected behaviour**
FF warning to trigger when you shoot an friendly, and the gulag to not harm you, just take you out of the action for a while

**Environment (please complete the following information):**
Version: unstable per date 28.07.2020

[ ] LAN Hosted
[x] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[x] Community Test Server 2

Modset:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 
ca. 14:00

**Comment by 1337zorn** [comment]
Ocean Gulag: (dude, that wording is bad)

Missidentified someone during firefight, posture crouched, and therefore TK'd someone. Got yeeted to the turtles. There was no Platform to sit on, no stretcher or anything, so i was swimming in the water.

After 120 secounds i was setPos'd back to the location i have been when the TK happend. 

Upon arrival I went unconcious (ace medical).

Did I took damage because I was swimming but then setPos'd on land so I collided with the Ground or sth?

Suggested Solution: Ad big enough platform to play with the turtles.

(also dont call it Ocean gulag)

**Comment by CalebSerafin** [comment]
Okay, I'll have a re-look at how the radio-fast travel moves the player, as the function used should be looking for a safe position in 50m. The animation is changed back to standing befor/during teleportation.

Everything will have to be moved to client-side to see if that affects whether the platform spawns or not. Changing the size of it won't help if it does not spawn.

An RPT would be lovely to see if there are any script errors, like null object references in case of the platform.

**Comment by CalebSerafin** [comment]
I'll investigate the vanilla RPG-7 and see what it's passing in its EH.

**Comment by CalebSerafin** [comment]
+ FF events may also return the vehicle that the instigator is occupying.

**Comment by CalebSerafin** [comment]
This should be solved, otherwise will reopen.
