### ISSUE TITLE
remove reb vs inv in parameters

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1352]
**Is your feature request related to a problem? Please describe.**
reb vs in is for the most part broken, it should not be an option until its working

**Describe the solution you'd like**
remove it as a value from the parameters, thereby making it no longer possible to run with it in a unedited version.

**Describe alternatives you've considered**
hard block on init? it would not really be a good solution

**Additional context**
dont think additional context is needed.

**Comment by jaj22** [comment]
I have a mostly-working patch that fixes reb vs inv by swapping all the template variables and tweaking the checks so that gamemodes 3 and 4 are treated identically. However, it has a couple of init order problems: 

- Clients don't currently wait for the server to initialize params (such as gamemode) before running initVarCommon, which is where side colours are initialized.
- Gamemode is currently loaded from saves, but this happens after initVarServer that would depend on it.

Not unresolvable problems, and I'm probably writing a patch for 2.3.1 to sort out parameter loading from saves anyway, but if these issues don't get fixed in time for 2.3.1 testing then disabling reb vs inv is the way to go.

**Comment by Bob-Murphy** [comment]
@jaj22 there is no real need to rewrite it for 2.3.1 as it will be completely obsolete with 2.4.
We could save the time we would need for the testing and use it on other topics.
