### ISSUE TITLE
High-Command AI spawning has no safety check

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1390]
**Is your feature request related to a problem? Please describe.**
AI squads with vehicles get spawned within already existing vehicles

**Describe the solution you'd like**
Implement the safety check we have for the other spawning

**Comment by jaj22** [comment]
It's using findEmptyPosition like most AI spawning, and works about as well/badly IME. It's just a bit more obvious when vehicles are exploding in your face.

I can try to fix safeSpawnPosition so that the AIs will actually drive afterwards, but it won't be flawless. Safe vehicle spawning is something that Arma should be taking responsibility for, and it doesn't.

**Comment by Bob-Murphy** [comment]
Should be 2.4 latest.

**Comment by killerswin2** [comment]
Using  the Garage Vehicle Placement HC squads are now placed safely, and John as already Implemented the fixes to safeSpawnPositions. If issue persistence reopen
