### ISSUE TITLE
Non-rebel event handlers may return 0 in some cases

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1398]
**Describe the bug**
Non-rebel event handlers may return 0 in some cases.
This can cause invincible AI.

**To Reproduce**
*This is where the trouble begins.*
Run with a HC to increase likely hood of bug occuring.

**Expected behaviour**
All event handlers return nil unless it is intentional 

**Environment (please complete the following information):**
Version: 2.3
Sahrani: 

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [x] Community Test Server
* [ ] Community Test Server 2
    
21:29 GMT+0:

RPT: no.

**Comment by jaj22** [comment]
Probably not our fault. As far as I can tell the only intentional HandleDamage that runs for enemy AIs with ACE is the top part of handleDamageAAF, which simply bails with an `exitWith {}`.

I've seen this with an ACE + HC test locally too. The invincibility was temporary and coincided with a lot of "network message delayed" logs. Because damage needs to pass client->server->HC to take effect, it's highly vulnerable to network issues or HC performance problems.

**Comment by Bob-Murphy** [comment]
@jaj22 So you deem this to be a non-fixable issue?

**Comment by jaj22** [comment]
I may have missed something, but I'd currently rule this as "not our fault" and also "no code-based workaround". It's possible that our scheduled code use is too heavy and that's bogging down the HCs, but I think ACE uses vastly more scheduled code than we do.

**Comment by CalebSerafin** [comment]
Closed until further eveidence that this is our fault or fixable from our side.
