### ISSUE TITLE
Flatbed unable to be sold fills up garage and wastes space

### ISSUE THREAD

**Issue by ShoppyCodes** [official-antistasi-community/A3-Antistasi#1488]
**Is your feature request related to a problem? Please describe.**
It's annoying that you can't get rid of unwanted flatbed trucks (the ones you can transport other cars on) by selling them. Either you leave them to get blown up somewhere or they fill up the faction garage and waste space.

**Describe the solution you'd like**
Enable the ability for the commander to sell Flatbed trucks.

**Describe alternatives you've considered**
Alternatively, if they aren't sellable for balance purposes then allow them to be sold for 0.

**Comment by Lazejun** [comment]
you misunderstood the whole thing

**Comment by Lazejun** [comment]
Disregard I miss read that 👀

**Comment by Lazejun** [comment]
Pretty sure its an Oversight since:
You can't sell:
vehFIAArmedCar
vehFIACar
vehFIATruck
vehNATOCargoTrucks
(There is no CSAT Variant)
vehCSATRBoat
vehNATORBoat
vehNATOBike
vehCSATBike
vehNATOUAVSmall
vehCSATUAVSmall
vehPoliceCar
NATOMG (ONLY on Vanilla due to the same on all 3 Factions, Sell price of SDKMGStatic)
staticATOccupants
staticAAOccupants
NATOMortar
CSATMG (ONLY on Vanilla due to the same on all 3 Factions, Sell price of SDKMGStatic)
staticATInvaders
staticAAInvaders
CSATMortar

BUT: You can Sell Planes, Drones, Tanks, APCs, Gunboats Attack Helicopters, Transport Helicopters etc.

**Comment by jaj22** [comment]
vehFIA(Armed)Car and vehPoliceCar are particularly annoying because you get a ton of them in the early game.

I don't think it's a balance issue. Anything in the 50-200 range should be fine for most of these.

**Comment by jaj22** [comment]
On second look, I think most of these are symptoms of slightly deeper bugs. The ground vehicles are almost certainly intended to go in `vehNormal` and hence `vehUnlimited`. vehNATORBoat and vehCSATRBoat are supposed to go in vehBoats.

Any statics or UAVs being sellable is an exploit if they're unlockable, because you can unlock the bags and then build and sell unlimited quantities. Device bags probably shouldn't be unlockable. Otherwise, I think making all statics sellable is fine.
