### ISSUE TITLE
PvP Players can join AI groups with ACE (again)

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1506]
**Describe the bug**
PvP Players can use ACE interact to join AI squads. This was previously blocked.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
Load in as PvP, use ACE to join an AI's squad.

**Expected behaviour**
Not be able to join group.

**Screenshots**
N/A
**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[x] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: RHS
    
Time the bug occurred (Please leave in GMT+0): 23:42
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Brandantl** [comment]
https://clips.twitch.tv/SourViscousClipsmomOSkomodo

**Comment by jaj22** [comment]
As far as I know, there was never any ACE group join blocking for PvP players. Blocking code was added late in 2.3 specifically for rebels joining other rebel groups, due to potential bugs with garrisons and HC squads. Before that, rebels could also ACE-join whatever they liked.

The current code isn't trivially extended to PvP players because you need to feed it with every target classname that needs blocking. It'd need to scrape all the gov & inv arrays for classnames.

**Comment by Bob-Murphy** [comment]
PvP will be disabled which makes this issue obsolete.
