### ISSUE TITLE
PvP Vehicle kicker not working

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1532]
**Describe the bug**
When PvP Players mount vehicles and enter seats they should not use (Driver/gunner etc (Any non-passenger)) they get the warning hint but it doesn't kick them from the vehicle.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
As PvP Mount any vehicle that they cannot spawn via a passenger seat then switch to the driver/gunner seat.

**Expected behaviour**
The player to be kicked from the vehicle.

**Screenshots**
https://clips.twitch.tv/ThoughtfulUgliestTurtleTF2John
https://clips.twitch.tv/ExquisiteCrispyMoonAliens

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[x] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: 3CB, RHS.
    
Time the bug occurred (Please leave in GMT+0): UKNOWN
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by jaj22** [comment]
I could semi-replicate this with a local DS:

1. The vehicle can't be local to the player, otherwise kicking is reliable.
2. Only the gunner seat worked on the M1045s. Driver seats kicked immediately.
3. Kick still happened in the gunner seat, but delayed by ~10 seconds.

This seems more Arma bug than Antistasi bug. Could try adding a sleep before the moveOut command (the relevant code is just `_unit spawn { moveOut _this }`) but I don't know if that's going to be reliable on a slow remote server.

**Comment by Bob-Murphy** [comment]
PvP will be disabled which makes this issue obsolete.
