### ISSUE TITLE
Get Rid of Vanilla Gunboats in RHS Templates.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1561]
**Is your feature request related to a problem? Please describe.**
In some of the Template we still use the Vanilla Gunboats, these spawn with Default Crew too, so Vanilla Equipment in a Modded scenario.
These can spawn during Attacks, and are usually Stationary at Seaports, if a Seapspawn Marker is within the Seaports Marker.

**Currently for RHS AFRF, RHS CDF**

**Describe the solution you'd like**
We can easily replace these Vanilla Gunboats with amphibious Vehicles from the Modsets.

vehNATOBoat,
vehCSATBoats,

BRDMs, BMPs, BMDs, BTRs there is plenty to choose.

**Comment by jaj22** [comment]
Spawning amphibious armoured vehicles on seaspawns? Not a fan.

Crewing vehicles manually rather than from config is something that needs doing anyway, so that seems like a better solution, assuming that we have any armed boats to work with at all.

**Comment by Lazejun** [comment]
Well for what reason exactly are you not a Fan?

They are slower, might pack more Armor, can have more or less firepower than The Gunboats, usually are not open so you can't just easily snipe the Crew as you can with Gunboats.

Of course it would be a Good source for X type of Vehicle but if it's just a Simple scout Cars as a BRDM it's effectivly less armed, less armored, less Powerful and not as broken as the Vanilla Gunboats 👀

**Comment by jaj22** [comment]
I might be underestimating the capabilities of the amphibious vehicles in question, but they don't seem to make sense in any of the three cases where boats are used:

1. Armoured vehicles parked in the sea at a harbour is just weird. Not exactly the natural habitat.
2. Sea patrols (eg for the Salvage mission). You don't send a slowly-paddling armoured vehicle to chase a boat, right.
3. Sea element of waved attacks. The issue here is that the distance from seaspawn to target can be very large, and if all the boats are extremely slow then it's going to look like the attack has bugged out.

Some of these could be mitigated, but in the current state of the code, simply replacing boats with amphibious vehicles doesn't feel like a good option.

**Comment by Lazejun** [comment]
Also done with Template rework, the Solution was using the RHS Soccom boat, it does not fit the Faction but atleast its not a Vanilla Gunboat
