### ISSUE TITLE
Arsenal allows players to load items not in arsenal, or items locked behind server membership.

### ISSUE THREAD

**Issue by ComboTombo** [official-antistasi-community/A3-Antistasi#1563]
**Describe the bug**
In some uncommon cases, the player is able to select a loadout from the arsenal containing items that aren't in the arsenal, and yet the arsenal will create these items out of thin air and give them to the player.
In other cases, the player is able to enter the arsenal and grab items that are locked behind server membership (aka not unlocked yet) when the player doesn't have server membership.

**To Reproduce**
Reproducing the bug of items being created out of thin air:
1. Enter the arsenal
2. Select loadout with items that aren't in the arsenal
3. Load this loadout

Yes, I know, this reproduction step is completely normal. According to the player reporting the bug to me, that's exactly what had happened. He was able to perform this multiple times, resulting in the unlock of the M21 M856A1 ammo, and a flavour of the 200 round M249 box, even though both items were not in the arsenal at the time.
NOTE: In order for you to create items out of thin air, you must make sure that your uniform/vest/backpack that has said items is unlocked.

Reproducing the bug of grabbing items that are locked behind membership:
1. Enter the driver seat of a vehicle
2. Drive up to the vehicle ammo box
3. Enter the vehicle arsenal
4. Click on the 3-magazines icon to the right
5. Most ammunition that's locked behind server membership would be up for grabs.

Make sure you have server membership on and that you aren't a member.

**Expected behaviour**
Arsenal should not create items out of thin air and give the player said items just because they're in the loadout. 
Arsenal should also not allow players to take items locked behind membership through the vehicle arsenal, whereas in the player arsenal said items would be locked as intended.

**Screenshots**
https://cdn.discordapp.com/attachments/730485457418321970/768731557442617344/20201022000214_1.jpg

**Environment (please complete the following information):**
Version: 2.3.1
Map (specify if Altis Blufor): Chernarus Winter

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [X] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: Community servers 3CB modset + CUP (for Chernarus)
    
Time the bug occurred (Please leave in GMT+0): 21st of October, 2215

**Additional context**
In both cases, these bugs have been found by the trial member "Sagitta". Additional information could be gained from extensive waterboarding. Repeated occurrences have lead me to believe there is a bug with the arsenal.
https://youtu.be/KbeHERT4zdo

.RPT file could be retrieved from the community's backend team (or any admin, really). I doubt it would have much information...

**Comment by jaj22** [comment]
The reproduction method for the first bug is incomplete. Loading the loadout "correctly" (ok, minor bug) caps the unavailable/locked magazines to zero bullets, so this won't generate any items as the arsenal counts bullets rather than mags. You need to exit the arsenal, enter and then exit again (yes, really) for the empty magazines to be topped up from thin air.

Second one looks like the member cap isn't being multiplied by the magazine size for the vehicle arsenal. I vaguely recall fixing this in the normal arsenal a while back.

**Comment by jaj22** [comment]
Ok, turns out that the first part is a BIS bug with setUnitLoadout. Looks like it always tops up magazines when there are multiple mags in a container (eg vest) with the same bullet count. If there's only one mag with each bullet count, then it works correctly.

The Antistasi arsenal uses setUnitLoadout on launch... because it's working aroung the underlying BIS arsenal topping up magazines. Isn't Arma amazing?

I think I can work around this by switching JNA's hacks around.
