### ISSUE TITLE
Roadblock/Observation Post deploying state intermittently does not reflecting the truth

### ISSUE THREAD

**Issue by Briggybros** [official-antistasi-community/A3-Antistasi#1612]
**Describe the bug**
Commander -> Deploy O.Post / Roadblock fails with "We can only deploy / delete one Observation Post or Roadblock at a time" when there is none being deployed or deleting

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):

1. Deploy an roadblock
2. Have the roadblock squad be killed en-route
3. Try to deploy a new roadblock
4. See above message appear

**Expected behaviour**
Can always deploy a roadblock / O.Post if there is not one currently deploying

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: 2.3.2 (also present in 2.3.1)
Map (specify if Altis Blufor): Altis

* [ ] LAN Hosted
* [ ] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: CBA_A3, RHSUSAF, RHSAFRF, RHSGREF, Emhanced Movement, DUI - Squad Radar, VET_Unflipping
    
Time the bug occurred (Please leave in GMT+0): 01:20GMT
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: GMT

**Comment by AlexTriada** [comment]
This is fake bug, checked, delete this

**Comment by AlexTriada** [comment]
wait 15 seconds after the roadblock squad be killed

**Comment by Briggybros** [comment]
@AlexTriada This is not a 'fake', I can reproduce it relatively consistently. The only way to resolve the issue at the moment is to restart the server.

**Comment by AlexTriada** [comment]
check your steps to reproduce, maybe you lose something

**Comment by AlexTriada** [comment]
after server start all works fine

**Comment by Lazejun** [comment]
well it's mostlikely another Victim of #1433


https://github.com/official-antistasi-community/A3-Antistasi/blob/e62a46e4356b5a952f9228347af58c9196bae370/A3-Antistasi/functions/Base/fn_outpostDialog.sqf#L3

**Comment by AlexTriada** [comment]
ok, maybe i am wrong, checking ...

**Comment by AlexTriada** [comment]
Yes, i can reproduce this bug, in the host server too

**Comment by AlexTriada** [comment]
the trick is that such a bug occurs only if you put a roadblock first, and then the second one causes this issue, so step to reproduce is put one roadblock, then try put second one and no way

**Comment by AlexTriada** [comment]
ok, if this is "task framework problem" this issue needs to rename or create new one,
- I can't stable reproduce this issue, most time all works fine

**Comment by Briggybros** [comment]
@AlexTriada I am unsure of a better title without knowing the exact cause. I will spend some more time trying to break it ;)

**Comment by Briggybros** [comment]
Possibly also caused by the commander leaving between roadblock deploying (task complete) and the roadblock spawning (troops + car appear in world)

**Comment by jaj22** [comment]
I can't replicate the example in this issue, and the case seems simple enough. The mission fails when there are no live units remaining in the group, and the task is deleted 15 seconds later.

Because the whole function (createOutpostsFIA) runs on the server, the commander has no influence here except in ordering the roadblock squad to the marker. You can swap commanders at any point without problems. Remote-controlling the squad is a risk but that's another can of worms entirely.

You can use roadblocks for a demonstration of a common problem in #1433 though. Needs a dedicated server: Start game, create a roadblock/post and send the units so it completes. Then start another roadblock/post but don't send the units yet. Log off, log back on and there will be a completed roadblock task and no task indicator on the map. The roadblock will still be created if you send the group to the correct location.
