### ISSUE TITLE
Error Zero divisor in the server RPT file

### ISSUE THREAD

**Issue by AlexTriada** [official-antistasi-community/A3-Antistasi#1658]
**Describe the bug**
A found this in the server RPT:

[arma3server_ds2_x64_2021-01-17_14-00-23.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/5826419/arma3server_ds2_x64_2021-01-17_14-00-23.zip)

```
16:19:01 Error in expression < = _x select 1;
_count = floor (_bullets/_capacity);
_magazine pushBack [_type,_>
16:19:01   Error position: </_capacity);
_magazine pushBack [_type,_>
16:19:01   Error Zero divisor
16:19:01 File functions\Ammunition\fn_arsenalManage.sqf [A3A_fnc_arsenalManage]..., line 1098
```

**To Reproduce**
-

**Expected behaviour**
no errors

**Screenshots**

**Environment (please complete the following information):**
Version:  2.3.3
Map (specify if Altis Blufor):  Virolahti

* [ ] LAN Hosted
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: RHS, CBA, TFR, CUP

**Comment by jaj22** [comment]
Apparently you have a zero-capacity magazine in the arsenal. I don't think that's been reported for any supported mod, but it'll certainly happen with a modset switch. Needs fixing because it might cut out the rest of arsenalManage.

As a broader point, arsenalManage probably shouldn't be processing anything that isn't currently a valid class.
