### ISSUE TITLE
Support rework balancing

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1902]
**What, in your opinion, is currently wrong with the balance?**
The community has reported several issues where they feel incorrect response from the enemy supports are being used and that the supports are too frequent, this makes the mission feel less enjoyable for most and needs to be addressed.

**Suggested changes**
from discussions within the community these following things have been suggested:
1. increase cooldowns for supports, (having a multiplier added for this too allows for communities to refine the cooldowns for their own taste)

2. restrict certain supports from targeting certain things, like mortars being used against cities etc.
Also making the support selection be more in favor of sending troops instead of dropping bombs or indirect fire.
as a final note support chaining should not happen, i.e. launching another support while a support is already being sent towards the target, this could exclude supports against specific assets like ASF/CAS to deal with rebel vehicles.

3. limit airstrike speed to `NORMAL` maximum for jets, as they feel far to quick to react for players atm, in addition a addition to the possible bombs used, whit FA bomb or something similar to be referenced over napalm, as it's currently too heavily used. potentially fully replace the current napalm or alter its behaviour to not be as brutal, the current biggest problem with it now being that it kills through walls guaranteed, making it only possible to survive it by not being inside the strike zone.

Note: whit the airstrike rework in progress, making airstrikes a lot more restrictive used would probably be a good idea.

**Comment by jaj22** [comment]
The trouble with point 1 is that the balancing for the supports is quite complex. There are multiple layers of restrictions:

1. Each group has a five minute cooldown between support calls. If the leader is shot before completing the call (10-15 second delay), the group must wait for the cooldown before a further attempt.
2. The same support can't be called twice in a row within 10 minutes (I assume to mix things up), however an instant airstrike-mortar-airstrike combo is possible.
3. A support can't generally be called within an active coverage marker for the same support type. Coverage markers for mortars are very large (3km radius), so only one is typically active within an area at once. However, airstrikes have tiny coverage markers (25x100m ellipse), so it's quite possible for multiple airstrikes to be in progress against effectively the same target.
4. There are a player-dependent number of timers for each support type. For example, airstrikes have 1 + floor(players/4) active timers. These are incremented by 30 minutes on support creation, so for 20 players, six airstrikes per 30 minutes is the maximum rate.
5. Supports are also restricted by available sources. In this example, airstrikes don't lock out airports, but do require that the airport is unspawned and hasn't been used recently for other purposes, eg. a QRF. Carriers/air corridors don't get this check, so they can always spam airstrikes within 10km.

As a result, support restrictions can sometimes appear reasonable, while sometimes you'll get spammed with six airstrikes in two minutes (real example). Due to the complexity and fragility of the restrictions, there's not necessarily any clear correlation with player behaviour.

Note that supports are generally not cross-constrained other than by points 1 and 5. Calling an airstrike on a mortar target is fine, for example.

**Comment by jaj22** [comment]
Support selection is split into two parts. Most support calls are generated through chooseSupport, which creates an ordered array of desired support types based on the enemies near the trigger enemy, and friendly squad members. It doesn't consider other nearby friendlies, enemies beyond 100m from the target, or supports already arranged. It has a bit of a downer on QRFs, only recommending them against 1-2 enemies.

The support routines themselves (starting from sendSupport) are apparently not supposed to contain any AI, so they simply check availability (hard yes/no) and pick the first available support from the input array. I think it'd be a lot easier to make the system respond reasonably with a more holistic analysis, but this is very different to how it's written at the moment.

**Comment by jaj22** [comment]
Rewritten in #2383
