### ISSUE TITLE
AI engi no backpack

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1929]
**Describe the bug**
Friendly AI engineer is spawning without a backpack (even tho unlocked) and therefore has no space for a toolkit

**To Reproduce**
Buy AI engineer

**Expected behaviour**
Have a backpack and enough space for toolkit

**Screenshots**
Doesn't matter as it's not visible on the screenshot that he in fact IS an engineer as we apply perks to riflemen

**Environment (please complete the following information):**
Version: VN-02

Did you make any changes to the code and if so, which changes:

Map (specify if Altis Blufor): CLN

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [x] Community Test Server
* [ ] Community Test Server 2

Modset: CBA, TFAR

**Comment by jaj22** [comment]
I can hardcode this as a quickfix but it's horrible, because the template system isn't passing the required data. Need to talk to Spoffy about switching the rebel loadout code over to a bunch of faction variables to be used from elsewhere. The fixed-loadout stuff just isn't compatible with the unlocked-items system used for rebels. We have to pick one or the other, and I prefer the arsenal dependency.
