### ISSUE TITLE
multi spawned statics in milBuildings

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1956]
**Describe the bug**
When multiple locations of type `outpost` or `airport` have overlap with its `marker size * 1.2` it can spawn multiple statics in the designated static spawn positions.
(scalable to N locations overlapping over the mil building in question).

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
spawn in a locations with a mil building being covered by multiple airport or outpost markers.

**Expected behaviour**
singular static in each spawn location spawned

**Screenshots**

**Environment (please complete the following information):**
Version:  2.4.1

Did you make any changes to the code and if so, which changes: No

Map (specify if Altis Blufor): 

* [x] LAN Hosted
* [x] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: Any
    
Time the bug occurred (Please leave in GMT+0): N/A
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

Note we could potentially solve this with registre on the buildings of which locations are spawning it in, and only create a static if no other location has spawned it yet.
we may also consider blocking spawning statics in markers that is not the markes spawning stuff. (locations outside markers would still spawn.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Bob-Murphy** [comment]
I just remember that is already fixed in VN-dev branch.
To give more info:
When I recall it correctly the current code in 2.4.1 is placing 50.cals in a radius distance around the flag which is  approx `(sqrt(marker_length²+marker_width²)) * 1.2` or something like that aka placing statics WAY outside of the marker area itself.

This has been fixed in VN branch and therefore this won't be happening. Especially as no marker is placed overlapping.
Change can be found in here: https://github.com/official-antistasi-community/A3-Antistasi/commit/9d08bf9bf028da1b665f2b5bc308795497d9a958
