### ISSUE TITLE
Feature Request: Add Info when last Garbage Clean happend

### ISSUE THREAD

**Issue by 1337zorn** [official-antistasi-community/A3-Antistasi#1991]
**Is your feature request related to a problem? Please describe.**
There is no ingame Info/Feedback about  when the last GC happend

**Describe the solution you'd like**
HQ Whiteboard - Action: "Game Options" triggers Hint with current Settings: 
=> Add another Line with "Time Since last Garbage Clean"

Optional: Add the Time since the last 3 Garbage Cleans

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
![107410_20210701173355_1](https://user-images.githubusercontent.com/56258612/124152593-f7f4df00-da93-11eb-8c9c-189700f9bd62.png)

**Comment by CalebSerafin** [comment]
Okay, only one last time span will be displayed. Previous GCs will need to be fished out of the logs (Or out of Giddi's bot's graph). This is due to the Game Options hint's high info population, and the last GC is the most important. 

I'll also add the last GC time span to the garbage clean message, so a random player can screenshot it if they would like to file a complaint against the commander.
