### ISSUE TITLE
Use of SetOvercast to remove Clouds

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1992]
**Is your feature request related to a problem? Please describe.**
SetRain doesen't remove Clouds, if its Rainy it's usually Cloudy aswell, removing the Rain will just remove the Rain but clouds remain, leaving the Map a bit Darker due to Clouds.

**Describe the solution you'd like**
SetOvercast 0 does remove the Clouds, making it Sunny again.
This might also be nice at night if clouds block the Moonlight leaving it darker than it has to be.

-----> Probably Adding Setovercast 0 to the Rain action or adding another Action just for Overcast.

**Comment by Bob-Murphy** [comment]
additionals:
- make the change take a little longer and not instantly (maybe 30 secs for rain to stop, 90-150 to get rid of overcast)
- make sure the button can only be pressed once and then is on a cooldown with a message like "you already prayed to the weather goats, chill out" or somethig like this (idiot save)

**Comment by jaj22** [comment]
Was gonna last-minute this, but ran into some questions:

1. Is setOvercast logically separate from setRain? Can you have rain with overcast 0?
2. If you can force weird values (eg. the rain 1, overcast 0), what does the weather progression do afterwards?
3. If we have a separate setOvercast function, what's a good name for it?

**Comment by Lazejun** [comment]
In Theory there can't / Won't be Rain with Overcast 0.

In practice there is Rain for a short amount of time but it will be gone if Overcast is to low.

The problem itself is that Rain and Overcast are linked, if Overcast is 1 and Rain is 0, Rain will just Rise very quickly and start to Rain.

On the Name question, no idea but I think Bob will like "Sunshine reggae"

**Comment by jaj22** [comment]
Further investigation: setOvercast seems to ignore the time parameter unless it's very high. Otherwise it's a very slow change, maybe an hour to get from overcast 1 to overcast 0. You can use forceWeatherChange to change it instantly, but that's not good visually.

Fairly long overcast delay seems ok to me though. If people are desperate for a faster change then they can always use Zeus.

Given the linkage between overcast and rain, I'm strongly inclined to put it on one control. Might go for 0.25 overcast rather than 0 though.
