### ISSUE TITLE
[Bug]: AT Squads / AT units don't have launchers

### ISSUE THREAD

**Issue by Enclave2020** [official-antistasi-community/A3-Antistasi#2122]
### Describe the bug

All AT units don't have any launchers until player unlocked unlimited launchers. Titan is Missle Launcher, so it can't be unlimited. Only Rocket Launchers, like PCML

https://github.com/official-antistasi-community/A3-Antistasi/blob/14d1505a278e0b198fa79962436c400f50766796/A3-Antistasi/functions/REINF/fn_equipRebel.sqf#L97

Doesn't looks like a feature. We loot every soldier for week and still have near 15 PCML.

### How to reproduce

Hire AT soldier or AT Squad, it will have only primary weapon.

### Version

2.5.2

### Have you altered the code?

No

### Map

Malden

### What server?

Private dedicated server

**Comment by jaj22** [comment]
Not a bug. I believe the argument was that you can't give vanilla a free rocket launcher because they're too strong in the hands of players (or the vehicles are too fragile). It's actually better than it was, because now 2/3 of regular squads have a guy with LAT.

Probably won't be dealt with properly until we remove unlocks.

**Comment by jaj22** [comment]
Fixed as much as it's going to be. In vanilla you now get *some* rocket launchers to start, with a small income. If you load Apex you get the BIS RPG-7 unlocked instead.
