### ISSUE TITLE
[Bug]: Dogs not despawning

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2211]
### Describe the bug

Dogs spawn in, they don't despawn.

### How to reproduce

Find a police squad with a dog.
Leave spawning range for a while.
Dogs still there (can see in Zeus interface)

### Version

2.5.3

### Have you altered the code?

Yes

### What i have changed

```markdown
PRs up to Jan 11, 2022:
#2205
#2207
#2210
#2209
#2181
#2187
#2194
#2182
```

### Map

Altis

### What server?

Community Test Server

### Time bug occured (Server time/UTC)

18:19 (UTC)

### Mods

```html
// Server
Antistasi Members Addon
TFAR Enforcer
// Client & Server
TFAR
Gruppe Alder Trenches
VET_Unflipping
@ZeusEnhancedACE3Compatibility
Zeus Enhanced
RHS: United States Forces
RHS: GREF
RHS: Armed Forces of the Russian Federation
Enhanced Movement
Community Base Addons
@ACECompatTHSUnitedStatesArmedForces
@ACECompatRHSGREF
@ACECompatRHSArmedForcesoftheRussianFederation
Advanced Combat Enviroment
```

**Comment by jaj22** [comment]
Ancient. Didn't think it was that important until I checked why the test server wasn't spawning singleAttacks and saw this:
![20220217061237_1](https://user-images.githubusercontent.com/562040/154416960-7ea1f26c-80cf-4f9a-b01c-7209006c037c.jpg)

That's roughly 110 dogs spawned on the single HC. Turns out dogs count towards allUnits.
