### ISSUE TITLE
[Feature] Investigate Save and Load missionNamespace file.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2444]
### Related problem

It's difficult to manage persistent saves.
Cannot split upa nd share specific saves, only large profile namespaces.

### Proposed feature

https://community.bistudio.com/wiki/saveMissionProfileNamespace can be used to save the missionProfileNamespace.

Note that there may be technical limitations of 5his command and how well it works with the established SQF save and load.

### Alternative solutions

Still continue to develop the save and load from string.
Use checksums, versioning  and validation similar to StreetArtist.

### Additional context

If you have any information regarding how well saveProfileNamespace works please post it in a comment.
Especially for how well this works with CBA and ACE event handlers.

**Comment by igorkis-scrts** [comment]
From what I can tell, It works fine for Antistasi Plus - I just replaced all `profileNamespace` calls with `missionProfileNamespace`  ones (and other related calls), moved storing `serverID` to from fn_initServer to fn_saveLoop (it didn't work for some reason) and it was a breeze since then.
Also, `missionGroup` field should be set up in description.ext's - otherwise each version will live in it's own namespace thus making carrying progress between versions impossible.

Can't say anything about ACE/CBA though.

**Comment by jaj22** [comment]
Might wanna wait until this is fixed: https://feedback.bistudio.com/T167316

**Comment by igorkis-scrts** [comment]
I've tested it with Antistasi Plus - it works, but due to that fact it loads too late in the mission execution order save file `initServer` can't get access in the first run to stored variables because they're not loaded yet (it works only with second+ runs  of the mission).
Anyway, it's almost there and it's almost ready for production - `profileNamespace` and related calls can be replaced with `missionProfileNamespace` ones just fine (still some tweaks should be made - missionGroup in description.ext so patches won't break saves continuity, also looks like `worldName` can be removed from vars. variable names too as it is no longer necessary to be there). 

One of the BI devs already moved missionProfileNamespace to load the namespace before initServer, but this version is not yet released (KK said that it will likely to be delivered via hotfix for A3 2.10).

**Comment by jaj22** [comment]
We'd still want to support old saves, so there's a bit of extra work involved beyond switching the calls. Probably group together the parameters required for identifying a save (including namespace flag) and pass those around so that most code is unaffected.

If we're sticking with the multiple vars per save system then yeah, `worldname` is obsolete in the save var name, as is `antistasi/antistasiB`. As far as I can tell, `serverID` never had any reason for existing and should be dropped too, which just leaves varname%campaignID.

I'm not sure on the current compatibility status for Community vs Plus. If we're going to attempt to maintain save compatibility in the future then we should use the same missionGroup. Otherwise we probably shouldn't.

**Comment by jaj22** [comment]
Implementation seems fine.
