### ISSUE TITLE
[Change Request]: AI Spawn Distance

### ISSUE THREAD

**Issue by Air989** [official-antistasi-community/A3-Antistasi#2547]
### Is the requested change related to a problem?

I and a couple of friends will attack a certain objective for instance an outpost they will stay with ground forces while I am in a Jet /Heli attacking from the air. When in the targeting system in the jet I only have a couple of seconds to target and lock on (if possible) to the projected target. By extending the distance I would have more time to align myself with the target and have better accuracy when attacking. Thank you all so much!

### Describe the solution you'd like.

I was wondering if there could be a change to the ai spawn distance limit on the game options tab to 4km or greater depending on the prerequisites that may currently be implemented.

### Alternative solutions

If not possible point me in the right direction to change the code myself:)

**Comment by jaj22** [comment]
You're doing it wrong. Just move your ground forces (players or high command units) in range of whatever you want spawned and then you can attack them from wherever. In the upcoming version, fast air vehicles no longer spawn at all because the perf cost of excessive spawning during overflight is horrible.

If for some reason you can't target units at long range when they've been spawned in by ground units, that's a different problem and not specific to Antistasi.

**Comment by Air989** [comment]
> You're doing it wrong. Just move your ground forces (players or high command units) in range of whatever you want spawned and then you can attack them from wherever. In the upcoming version, fast air vehicles no longer spawn at all because the perf cost of excessive spawning during overflight is horrible.
> 
> If for some reason you can't target units at long range when they've been spawned in by ground units, that's a different problem and not specific to Antistasi.

Okay thank you, my friend!
