### ISSUE TITLE
QRF are way to strong

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#298]
As title states, QRF are way to strong since 2.x, MBTs on war level 2 is extrem harcore

**Comment by Toakan** [comment]
This needs to ramp up from gradually, rather than suddenly danger.

Something like:
Level 1 : Prowlers 
Level 2 : Hunters W/o Guns + Prowlers 
Level 3 : MRAPs  (Hunter W Guns)
Level 4 : MRAPs + A single APC 
Level 5 : 2x APC 
Level 6 : 3x APC + Multiple MRAPs
Level 7 : Multiple APC + 1 MBT 
Level 8 : MBTs'

**Comment by Spoffy** [comment]
I don't believe Wurzel has touched QRFs at all yet.

**Comment by wurzel0701** [comment]
Actually yes, they are just not getting called right now.
So in the end, it is a no

**Comment by wurzel0701** [comment]
Vehicles are now locked by warlevel, closing this issue
