### ISSUE TITLE
[Bug] ACRE2 Integration Not Working

### ISSUE THREAD

**Issue by Godlikehobbit** [official-antistasi-community/A3-Antistasi#322]
### Version of the mission:

* [x]  A3-Antistasi 1.9 - Community Version (1.9.1.3D)

### Mods:

* [x]  CBA_A3

* [x]  ACRE2

* [x]  ACE

* [x]  RHS

### Environment:

* [ ]  SP
 
* [ ]  MP host server

* [x]  MP dedicated server

### .rpt file attatched?

* [ ]  YES

* [x]  NO

### Do you edit the mission file?

* [ ]  YES

* [x]  NO

## Issue:
---

ACRE2 Radios (AN-343 etc.) appear under the bipod slot in the arsenal instead of the radio section and are unable to be added to a player inventory, the can however be added to a vehicle inventory. Additionally, calling in the USMC Support requires a radio item in the inventory but does not recognize the ACRE radios.

**Comment by Bob-Murphy** [comment]
Hi Hobbit,
ACRE2 was integrated a long time ago and we have never updated it or even looked at it as we use TFAR on our servers.
We most likely will look at it at some point in the future so it's not on our "needs fix immediately" list. But we are aware of that problem. Thank you for the issue.

**Comment by Godlikehobbit** [comment]
It is working perfectly fine on the A3-Antistasi - Altis BLUFOR - Community Vers. just not the 1.9 edition. Just fyi

**Comment by Bob-Murphy** [comment]
Oh wait, I just saw that you ticked that this is a Antistasi 1.9.1.3 problem but you have posted it in Antistasi 2.1 (former 1.4).
Could you please verify that it is indeed 1.9? Because if so, we won't fix it at all as we are not working at 1.9 at all.

here the link to the 1.9 repo where you clearly find that it's not being worked on
https://github.com/official-antistasi-community/A3-AntiStasi-1.9-outdated

**Comment by Godlikehobbit** [comment]
Oh my bad haha, got my version's mixed up/didn't realise that the 1.9 version was outdated/EOL'd, thanks for the help

**Comment by Bob-Murphy** [comment]
Most welcome nevertheless!
