### ISSUE TITLE
[question] Add -1HR when player died

### ISSUE THREAD

**Issue by AlexTriada** [official-antistasi-community/A3-Antistasi#323]
## Issue:
It is necessary to add -1HR when player died for realistic expirience
There is only penalty % of player money now, it's make players infinitly respawn and respawn.

**Comment by SonorousMeerkat** [comment]
What should happen at 0 HR?

**Comment by AlexTriada** [comment]
Nothing

**Comment by SonorousMeerkat** [comment]
As in they can spawn as normal? (presumably without sending HR negative)

**Comment by AlexTriada** [comment]
> As in they can spawn as normal? (presumably without sending HR negative)

When HR present, -1HR is working, when 0 HR still 0 when player died

**Comment by SonorousMeerkat** [comment]
Interesting suggestion, and timing for it, as we recently had a very short chat about possibly changing the penalty for dying. We'll keep it in mind.

**Comment by Spoffy** [comment]
We've had a talk about this, and decided that while it does increase the penalty for dying, and deter suicide tactics - it isn't the right way to solve this problem for two reasons:

- It punishes low player count servers more than high player count servers.
- It's unlikely to be an important consideration when attacking, just an unfortunate side effect. Dying isn't something people normally choose to do.
- It makes the game harder, but not in a fun or interesting way.

**Comment by Bob-Murphy** [comment]
This really is a change in gameplay as especially at the start is not easy to gain HR but depending on the settings you have and how many people are playing, it's really easy to die.
This change seems logical because -1HR when a person dies is just logical but to be able to have something like this we would have to overhaul the complete HR system and not only change one variable in a working system.
