### ISSUE TITLE
[Game balance]: The response to rebel air is unbalanced

### ISSUE THREAD

**Issue by Tiny-DM** [official-antistasi-community/A3-Antistasi#3246]
### What is wrong with the balance currently?

Rebel air incurs a disproportionate response from the enemies, resulting in a variety of enemy ASFs, unavoidable missiles, and general pain and suffering. A rebalance of some sort needs to happen, whether it's improving the fighter AI, lowering the frequency, increasing the response time, or adding SAMs into the mix. 

### Describe the solution you'd like.

My personal preference is a mixture of all of the solutions mentioned above. The support response time needs to be increased as a first step, but after that the frequency of the fighters can be reduced to allow more uptime, and if too many fighters are taken down  a nearby airbase can begin harassing an uncooperative air target with SAMs to force it to land. This rewards more experienced pilots with longer uptime while also ensuring that you cannot be in the air forever.

### Alternative solutions

The SAMs or other air-to-air missiles could be a different class with the `cmImmunity` trait in their config, to make them harder to dodge. Another solution is removing SAMs from unfair supports and placing them as a normal support, so fighters are threatened wherever they go. The distance at which the aircraft spawns from the target could be increased so it's not necessarily on the airbase when it spawns as well, giving it plenty of time to close the distance.

### Additional context

As soon as you cross over or close to your first enemy outpost, a timer starts. This timer's length is dependent on war level and aggro, but is typically close to 2-3 minutes in an active area. You begin to attack your assigned targets, performing one, run, two runs. Your two missiles manage to destroy an APC and disable a tank. The players on the ground are proud of what you have done.

Unfortunantly, the enemy faction has decided that your ability to use your CAS aircraft should be revoked. A 4-5th gen fighter of your choosing spawns approximately two kilometers behind you; you check your RWR three seconds later for targets and see the half yellow, half white, one dot, and all death-causing fighter that has only one goal in mind: The destruction of your rebel aircraft.

You immediately switch to defending, begin pulling a high-G turn to get your missiles on target, or maybe you begin dropping altitude to evade. Your actions don't matter, unfortunately; the fighter was acquiring a lock the moment it appeared from thin air, and launches a single semi-active radar-guided air-to-air missile. You acquire a bead on the target and begin dumping flares to attempt to evade the missile, but it is no use. The Fox Three suddenly disappears from your RWR, presumably exploding mid air, before impacting your left engine with no warning whatsoever. As you go unconscious, you think to yourself what you could have done differently, but quite frankly? The only winning move is not to fly.

**Comment by jaj22** [comment]
One of the core issues is that the current air response rate/chance is super-dumb. Ground responses use a pretty complex location+threat based decision system, but that doesn't work for air vehicles at all due to their speed. Instead it's a straight call->response system, with a global cap of 30% max resources spent on anti-air. As far as I can tell there's also an ancient bug/misfeature where flying near an airfield will continually spam calls.

I think I came up with a system that might work and doesn't require a complete restructure. What you'd do is use the server's EntityKilled EH to add to the threat rating of the aircraft that dealt the damage, and then use that for response ramping. Depending on the enemy's available resources, simply entering a no fly zone might not provoke a response at all, while persistent air threats would draw the SAMs or the cmImmunity cheat.
