### ISSUE TITLE
Problems with rebel AI launcher unlock lists

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#332]
The logic we use to classify AT vs AA launchers for Rebel units does not always succeed in classifying all launchers. This is my second attempt at an implementation to solve this and currently needs more testing.

also exists here: #395 

https://github.com/official-antistasi-community/A3-Antistasi/blob/d36db2bc5888d722204ca87683bea0de3af49252/A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf#L87-L126

**Comment by jaj22** [comment]
I think lockAcquire is a dead parameter. It's wrong in both directions: The vanilla PCML has lockAcquire = 0, for example. The RHS RPG-7 also has lockAcquire = 1, which means AIs lose access to it when you unlock the SMAW. canLock seems more consistent but doesn't distinguish between the PCML and the Titan.

While you could probably identify the desired subset of launchers by checking a few poorly-documented config vars, I think you're better off hardcoding arrays of launchers and launcher ammunition to block from unlocking. I'm used to trawling the configs, so I can throw something together if that's an acceptable solution.

**Comment by PoweredByPot** [comment]
I did try another implementation that I haven't really had a chance to specifically and thoroughly test yet. Wait until that gets pulled here shortly and then I would be happy to hear any input you have on how to improve it

**Comment by jaj22** [comment]
The canLock parameter works as expected for vanilla & RHS at least, so that part should work. I don't think nameSound is useful though: The vanilla AT and AA Titans both use "aalauncher", and so do the RHS Javelin and Stinger. The PCML uses "atlauncher" but it counts as a rocket launcher anyway, not a missile launcher. 

I can't find a reliable method to distinguish between AT and AA missile launchers without checking right down to CfgAmmo (airLock = 2, probably). Not a critical issue unless you want AT AIs to use fancy launchers though.

Unless I've missed something, you're not restricting magazine unlocks at all, which would allow easy unlocking of fancy launcher ammo, regardless of the value of allowGuidedLaunchers. That doesn't look intentional. Could maybe test CfgAmmo -> weaponLockSystem in cases where the magazine count is 1.

**Comment by Bob-Murphy** [comment]
@PoweredByPot 
Update?

**Comment by Spoffy** [comment]
I've written a robust function for detection in 6e62b65530c720393d239523a0b862ab936a5aa0, that looks at Ammo, and handles weird ACE/Disposable edge cases accordingly.

Unlock lists are correctly sorted in c2745c4917beedc00c00621c0a881537c5f7d8d9
