### ISSUE TITLE
[Feature Request]: Drones to buy

### ISSUE THREAD

**Issue by Rallo00** [official-antistasi-community/A3-Antistasi#3336]
### Related problem

As drones are pretty easy to find on the market even for civilians today I am suggesting to add the Possibility to buy drones to use as fpv kamikaze drone (Ukraine war style), and possibility to drop explosives.

This is a good explanation of how real drones work in the current Ukraine/Russian war environment. 
https://www.reuters.com/graphics/UKRAINE-CRISIS/DRONES/dwpkeyjwkpm/

several scripts have been made for this but it would be nice to use it in antistasi as a cheaper artillery, also might provide a little realism if a person stands back to have a little eye in the sky targeting movements and giving orders to other players. Might be interesting for a good scenario like this one. 

### Proposed feature

As above.

**Comment by Bob-Murphy** [comment]
Hey,
cheers for the feature request but this is nothing we aim to implement, at least from the current standpoint.
Reason being, it would be insanely overpowered, the AI would have nothing to counter it and it would chance the balance of the gameplay in a which we do not intend to.
Also, as the only asset which could be lost by the player is the drone, the fact that he intends to blow it up either way does not even provide a situation in which the player would be afraid to lose something, like for example a fancy artillery piece which got looted.

In addition to that, not a decision-related fact but more for your information, because you brought up the current Ukraine/Russia conflict, we tend to stay away from ongoing conflicts and not involve/represent them within Antistasi

Thank you for your understanding.
