### ISSUE TITLE
Create 'Faction Specific' template files

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#386]
Unify the template files for each 'Faction', (i.e, Mod/Side combination) so that they can be spawned in any role - Invader, Occupant or rebel.

This depends on #385 to work.

**Comment by Bob-Murphy** [comment]
@Spoffy 
Update/Project?

**Comment by Spoffy** [comment]
Needs doing, needs #385 doing first.

**Comment by SonorousMeerkat** [comment]
What does this mean exactly? i.e. what should be done, as currently they use unit classnames that specify the side of the unit. I'm assuming PvP loadout style gear identification.

**Comment by Spoffy** [comment]
Probably best discussed on Discord.

**Comment by jaj22** [comment]
As a more gradualist approach, I think you can implement #386 first and then expand it later with #385. All classes in a faction template would need to be the same side/colour, but otherwise you could mix and match blue/red/green factions. For example, redfor occupants would be possible, enabling removal of the broken reb vs inv mode.

I see two basic options for role-flexible templates. You could pass faction objects and have the templates call setVariable directly on those, or have the templates write to uniquely-named globals and then shim those over through missionNamespace. The latter would have simpler template syntax, but would be more complex elsewhere.

**Comment by Bob-Murphy** [comment]
This will be fixed by the new template system.

**Comment by killerswin2** [comment]
as Frost said: "This new template system is now in the game."
