### ISSUE TITLE
Adapt the A3DD stuff so retards like me can use it :)

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#389]
Please adapt the A3DD code on your side and maybe also put it in a new repository i then can open here so others can use that fancy shit.

Also, please adapt so even I can use it :D

**Comment by CalebSerafin** [comment]
Funny thing is I offered it to the Dev team months ago, but was turned away because it only works on windows. I'm rewriting it to be work in other setups.

But if you take it right now put it in your respority root folder (same folder the git ignore is in). Run it once, press `y`, it will open up the config location. Open template.selected.cfg and navigate to the line `A3Profile=FrostsBite;`. Replace `FrostsBite` with the profile name you launch Arma 3 with.

Now evertime you run A3DD, it will create mission files inside your mpmissions with the same name as the mission template folders in Antisatsi/Templates (ie `A3-Antistasi.altis`). Now you can run these missions inside multi-player LAN host 

If you want copy these files somewhere else, go to documents/Arma 3 - Other Profiles/MyProfileName/mpmissions.

Just realised I don't have a detailed tutorial on the respority, so ctrl+C ctrl+V.

**Comment by Bob-Murphy** [comment]
Would it be possible to adapt it so it's only creating the folders locally?
Example:
I have the A3-Antistasi folder from the GitHub copied into G:\Antistasi\Finished releases\A3-Antistasi-2.1.2 (which is my version control system) and then would like to have created all the missionfolders within the same folder.
What also needs to be implemented in the folder-name is the version number.

Also, please keep in mind that I changed the position of the map templates in the GirHub folder structure.

**Comment by Godlikehobbit** [comment]
I'll write a powershell script to compile it but it'll need VS2017 Build tools and .NET 4.7.2. That's the easiest option unless Caleb wants to set up automated builds

**Comment by CalebSerafin** [comment]
Bob, if you click on a. sqf will it run in windows? Find the compiled exe in releases. :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by CalebSerafin** [comment]
But V2 is in the works, I just haven't had anytime to finished it.

**Comment by Godlikehobbit** [comment]
Yeah, nah, good powershell scripts for .NET compiling are not fun. Just stick with the release version

**Comment by Spoffy** [comment]
I've written a quick powershell script to do what Bob wanted. It just builds a folder for each map, with all the appropriate files copied in.

**Comment by CalebSerafin** [comment]
Done. Please see [Arma-3-Dev-Deploy](https://github.com/CalebSerafin/Arma-3-Dev-Deploy).
Read the howto on [README.md](https://github.com/CalebSerafin/Arma-3-Dev-Deploy/blob/master/README.md).
Find the two executables in release [b1.2](https://github.com/CalebSerafin/Arma-3-Dev-Deploy/releases/tag/b1.2).
Need more volunteers to test it on their machine and with their setups. But I hope to add it to the official repository.
