### ISSUE TITLE
Give sufficient equipment to friendly infantry

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#406]
Currently, friendly infantry spawn with barely any ammo, grenades or medical supplies. And I believe that's been the case for a long time. This should be addressed in the near future.

**Comment by Bob-Murphy** [comment]
@Spoffy 
Has this been fixed? If so, please comment, close and give the correct milestone.

**Comment by Spoffy** [comment]
This hasn't been fixed, no. It needs to be worked on.

**Comment by PoweredByPot** [comment]
@Spoffy 

5 magazines for the selected weapon are assigned from fn_randomRifle.sqf

_1_ FAK is added in fn_reDress (only called on rebels _if_ they arent wearing a proper rebel uniform).

2 smoke grenades are added in FIAinit and FIAinitBASES respectively.

**Comment by jaj22** [comment]
The FAK should probably be moved from reDress to FIAinit/FIAinitBASES. Makes it quite difficult to revive them at the moment. Also the medic should get a medikit so that they can do their job properly.

A slightly trickier issue is that at least in vanilla, a large quantity of unarmored vests and headgear are unlocked by default, so even once you've unlocked a lot of gear, your troops are still dying very easily.

**Comment by jaj22** [comment]
Also randomRifle always adds `1Rnd_HE_Grenade_shell`, which isn't compatible with the RHS AFRF grenade launchers.
