### ISSUE TITLE
Adjust loot crate defaults

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#411]
Look over the loot crate default parameter values, and see if they need balancing.

**Comment by wurzel0701** [comment]
This will need playtesting. This cannot be done by looking at the code if I am correct

**Comment by PoweredByPot** [comment]
correct, this is going to need long-term tweaking and adjusting. I really just need everyone to start play testing and tell me what they think.

**Comment by Spoffy** [comment]
Launcher shortage, optics shortage

**Comment by PoweredByPot** [comment]
Both are good examples of the same issue. Some items tend to get drowned out by the overall volume in their categories. Optics is slightly simpler because the default rate for them was always quite low, and then they got added to part of a larger category. That could be fixed just by raising the default parameters.

Launchers are a little more complex because of the breadth of the general 'Weapons' category. The solution is essentially to split each item into its own category with different rates so it is more properly represented. Eventually we have to worry about the performance of spawning a crate with so much "thinking" happening in the background. We also have the parameters to consider, and I don't want to add a crazy ton of them based on specific item classes being tweaked.

**Comment by jaj22** [comment]
Played with this for a while. Optics were fine after bumping up the category by one notch, although there may be minor subcategory problems. Launchers definitely need a subcategory, as they get flooded out by exotic rifles. If anything the general weapon count is too high, especially the stack size.

Ammunition for crate weapons feels unintentionally low. Surely you didn't really intend 1 clip per stack rather than at least 1 clip per weapon? With ammunition unlocking fairly easily and weapons sharing ammunition it's not always a problem, but we do have some unlocked weapons with 2-3 clips total. The separate crate ammunition routine doesn't seem to compensate sufficiently, even with the low ammunition unlock threshold, maybe because it also includes launcher ammo and grenades.

Unlocking mechanics are interrelated, so I'll mention them here. Unlocking launchers becomes extremely important when you have a low player count, because AIs in 2.2 will not show up with them otherwise. In vanilla, unlockable launchers are rare in the wild, so you are dependent on crate launchers to progress to midgame. The PCML currently unlocks instead of the MAAWS, which I assume is a bug.

Items with different camo unlocking separately is annoying, and sometimes crippling (there are three different colors of MAAWS mod 1 launcher, for example). I don't know if there's a good workaround for that. It might help if items (or at least launchers) used by the faction you're fighting had their own crate category, so those would unlock more reliably.

Titan ammunition currently unlocks disturbingly easily (you find about 3x as much as launchers), so players can deal cheaply and easily with armored vehicles and aircraft from an early stage. Losing the occasional launcher is not a problem. In general, ammunition unlocks too easily (should probably need 3-10x as many clips as weapons), and guided missiles probably shouldn't unlock at all by default. If so, ammo crates would need to be a relatively reliable source.

**Comment by Spoffy** [comment]
Awesome, thanks for the detailed feedback jaj, this is exactly the kind of awesome info we need to balance these types of feature before release. I don't think in there I disagree with, so you can be sure most, if not all of this will be sorted before 2.2 drops!

**Comment by Spoffy** [comment]
Resolved in #488 with commit c021fa7aa43ff6e7316c88d5009f8639cd4d9584

If there's any other issues, or you think more tweaking is needed @jaj22 - please don't hesitate to let us know!

**Comment by Spoffy** [comment]
Also @jaj22 - You can enable unlocking missile launchers in the server config, if you need it.

Camo is a good point, and I've opened #491 to make sure it gets addressed
