### ISSUE TITLE
Reorganize Labels

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#416]
We get like a million of it and at least I have lost track of it. Can we get it down to 10 maybe with only the really important onces and remove all others?

**Comment by Bob-Murphy** [comment]
How dare you give me work (which I already gave myself but of course forgot about...)?
It's my job to give you work!

**Comment by Bob-Murphy** [comment]
Done.
Deleted a bunch of labels and color-coded the remaining ones.
Red color: This are the labels with the most important information and should be focussed on.
Blue color: This are informational labels which indicate what this issue/PR is about.
Bright green: Basically indicate that a problem was (positively) completed. Either because it's fixed or it can be closed because another issue/PR is already working on that.
Weird colour: Just to get attention to Suggestions so we don't loose them within the pile of issues and PR's.
