### ISSUE TITLE
JNL Vehicle detection isn't fine grained enough

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#469]
Zil131 in the RHS mods is an example of why. Several variants exist with different seat mappings, but all share a common model. Therefore JNL crates can be loaded into any of them, but different seats get disabled in each.

**Comment by Spoffy** [comment]
Bug AND enhancement because it's an improvement to JNL, but also the Zil 131s have some buggy rendering from certain seats, when a crate is loaded.

**Comment by jaj22** [comment]
Ok, I eventually figured how this works. The cargo seat positions are selected from the model data using the `cargoProxyIndexes` array, so if the model name _and_ that array match, then the seat mappings should be valid across different classes.

There's a slightly weird aspect that some truck seats are considered to be turrets rather than cargo. In  I'd be surprised if there were any cases with the same model and cargoProxyIndexes but different turrets, but if that's a concern then the `getInProxyOrder` array should be a more accurate alternative, if a little longer.

I can have a crack at this tomorrow. Currently leaning towards model + getInProxyOrder comparison.

**Comment by Bob-Murphy** [comment]
Which is the intended milestone for that?
Is somebody already working on it?

**Comment by jaj22** [comment]
I shelved this to work on more important fixes, but I have a solid plan for it which shouldn't take more than a couple of hours' work. Let me know if you want it bumped up the priority order.

**Comment by jaj22** [comment]
I'm planning to do it once I run out of higher-priority bugfixes. Shouldn't take long to implement, as the research is done.

**Comment by SonorousMeerkat** [comment]
I believe I've got the seats right in my polishing work. AFAIK the seat mappings were the same, backup plan would be to disable seats 1-x to get rid of all additionals.

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat Please check the Zil131 just to be sure and then we can close the issue until a new issue arrises.

**Comment by SonorousMeerkat** [comment]
Update: I have disabled the Zil from the loading entirely and i am going to remove it from the templates in the future. RHS fucked up the seats _hard_ several of them clip and the numbering is seemingly at random.

**Comment by Bob-Murphy** [comment]
Ok. The general topic here is done and the only task is removing the ZIL.
I've opened a seperate issue regarding this which is #679  and therefore I consider this one closed.
