### ISSUE TITLE
Make weapon variants unlock base variant

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#491]
Issue is primarily with multiple camos failing to unlock the base (a base?) version of the gun. You can have 30 of 4 different camos, same gun, and no unlock.

**Comment by jaj22** [comment]
From a browse through the config classes, it looks as though matching `model` would have the desired result, at least for vanilla and RHS. In theory it might be possible for physically different weapons to share a P3D and switch parts of the model using `animationList` (like with the trucks), but I haven't found a practical example.

Even so, it's going to be mildly annoying. You'd need to build groups of weapon base classes with matching models, and then expand the arsenal unlock check to count and unlock those groups, not just the individual weapons. I think you can at least avoid messing with JNA itself though, and because the arsenal unlock checks everything at once it should be well suited to a conversion. Even more config scraping at startup though.

Note that if you do fix this without building it into the crate loot generation, it will then be much easier to unlock weapons that have multiple camo schemes than those which don't. Maybe not the intention.

Another aspect of the more general problem: If a modset has a large variety of gear in a category, then it'll be relatively difficult to unlock them with crates. While you could proportionally increase the size of the crate stacks to compensate, that would cause other balance problems with magazine unlocking and non-unlocked weapon use. Alternatively, you could decrease the unlock count of crate-only weapons proportionally to the variety, but there was already an objection to scraping that information.

**Comment by Spoffy** [comment]
Good idea of on matching the model - could work.  but yeah, any which way it's done is going to be a pain in the ass. 

Nice little observation on the camouflage too - you're absolutely right, that could make quite a significant difference. 

Regarding the size of the category affecting ease of weapon unlocking - you're absolutely right, this is a though I've already had. I've got a couple of ways to avoid the problem in mind, but I don't particularly want to implement them until we've tested the current implementation, because I'm not sure it'll be a huge deal. There's not enough launchers in the game for it to be a massive problem there I think, which would be my main concern with something like that.

**Comment by Bob-Murphy** [comment]
Which is the intended milestone for that?
Is somebody already working on it?

**Comment by jaj22** [comment]
Had a shot at implementing this. It actually works well from a technical perspective, but the model parameter isn't great. In vanilla, most key items have separate models for different camo: The MAAWS and all the optics and suppressors, for example. It's rather more effective in RHS, but you get the notable false-positive of the M136.

Might be worth including just to make it a bit easier to unlock guns in RHS, but I'm inclined to wait for feedback.

**Comment by Spoffy** [comment]
How many have a common superclass? Could you combine that with model to good effect?

**Comment by jaj22** [comment]
Superclasses would detect all or almost all of the valid matches, but you'd have a lot of false parentage to deal with. For example, most of the vanilla suppressors inherit from `muzzle_snds_H`, which is a real item.

I don't think there's a valid automated distinction, as the tree depth is so variable: You'd either need to make a blacklist or whitelist of appropriate parent classes. This would work, but it's getting increasingly close to a messier version of curated lists.

**Comment by Bob-Murphy** [comment]
This whole problem gets more and more complicated with every mod, as they all have different sorting systems, right?

**Comment by jaj22** [comment]
I doubt RHS generates many additional problems there, simply because vanilla already abuses inheritance. Anyway, there are two possible problems with the class parent whitelist method, both likely rare as I haven't seen any examples yet:

1. Classes that have both camo variations and substantially-different children.
2. Near-identical items sharing no similar parent.

Can't tell whether these are real issues without going through every case manually.

**Comment by Spoffy** [comment]
One 'solution' (workaround?) Might be for unlocking a base weapon to also unlock all variants.

**Comment by jaj22** [comment]
That part is fine. You can do this once you have a list of variant groups:

1. Add all variant counts to the first version for arsenalManage.
2. When an item in the variant list is unlocked by unlockItem, unlock all variants too.

It's fairly clean, quick and even works with old saves. Only problem is detecting the variant groups reliably.

**Comment by Bob-Murphy** [comment]
Before anybody touches this project, I would like to have Meerkats as well as Spoffys template stuff completed.
I know that it might not be exactly within the same spectrum, but it seems to be too close and could be influenced by it and therefore would needed to be touched again.
