### ISSUE TITLE
Open testing error 9 – Auto-completing missions

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#551]
**### Please assign yourself to the issue or comment your name when you start working on it.**

As visible in #2_2-bugs-for-current-text-version on discord we have a problem with auto-completing missions. Missions which were reported to auto-complete were at lest the following:

- [ ] Destroy mission (roadblock)

- [ ] City supply mission

Additional information about what maybe could be the cause can be found within the discord channel.

**Comment by CurePindal** [comment]
It seems we also had a "take outpost" mission autocomplete.

**Comment by jaj22** [comment]
On the city supply case, the example I saw seems to be a bug in the BIS task functionality, as there were two missions in the list with the same tag, which should be impossible. Anyway, the mission worked fine other than the task display, and given the lack of reports it may be extremely rare. Can ignore for the moment, I think.

Roadblocks can be destroyed accidentally by AI traffic accidents. I'm not sure if there's another case, but I think I've only had one autocompletion in testing since #569, which isn't enough information to work on. Would recommend closing or shelving pending further info.

**Comment by Spoffy** [comment]
Based on recommendation, I'm going to remove it from milestone 2.2 and tag with needing further info.

**Comment by Bob-Murphy** [comment]
As far as I know this one is not happening anymore and can be closed. Any objections?

**Comment by jaj22** [comment]
I would say close, and raise mission-specific issues if it happens again. Missions all have their own completion mechanics so a general issue isn't appropriate.

**Comment by Bob-Murphy** [comment]
Closing this for now.
