### ISSUE TITLE
Open testing error 13 - Review airstrikes

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#555]
During testing of 2.2 airstrikes also got send to city supply missions.
This should be reviewed and perhaps overhauled.
Additional information like visible in the picture below available in the #2_2-bugs-for-current-test-version discord channel.
![image](https://user-images.githubusercontent.com/50651578/69504182-cfece380-0f20-11ea-9009-13da88b7fec4.png)

**Comment by jaj22** [comment]
Later down the conversation we figured that the City Supply mission launches an airstrike with PatrolCA as a rule. Normally the airstrike is cancelled because NATO won't bomb within 300m of civilians or their own troops, but the test server may have been running without civs at the time.

Could be an old bug, and it was supposed to send an MRAP or something instead.

**Comment by Bob-Murphy** [comment]
Regarding the airstrikes:
If I'm informed correctly the bomber are spawning within a certain distance to the target, then bomb it and then despawn in a certain distance.
It makes no sense to have randomly spawning airplanes on the map, therefore it should be changed that the planes for example are spawning at airbases and after the attack fly to the carrier to despawn there.

**Comment by Bob-Murphy** [comment]
In correlation with #524

**Comment by wurzel0701** [comment]
Gone with the new support system
