### ISSUE TITLE
2.2 Surrendered soldiers and their crates dont vanish

### ISSUE THREAD

**Issue by CurePindal** [official-antistasi-community/A3-Antistasi#589]
*Version:* 2.2. (latest files)

*Mods:* none

*Environment*: MP dedi.

*.rpt attatched?* YES

*have you edited the missionfile?*: No

***Issue:***
Surrendered and interrogated enemies and their dropped crates dont vanish and keep littering the world.
I think this issue isnt new but still an annoyance. Even after coming back to an outpost we attacked over an hour ago the surrendered enemies/crates have still been there. Manual garbage collection ignores them too. Server restart removes them, ofc.

Expected: Automated garbage collection removes surrendered enemies/crates after a while, or you could still release them, so they run away. 
And/or: manual garbage removal removes them.

**Comment by jaj22** [comment]
Surrendered enemies are a weird case because I think they retain their groups, which should already have a despawn mechanism. I would expect them to disappear if everyone moved out of spawn range, but it may depend on the group's origin.

The crates do seem to be missing any despawn mechanism. Should probably be handed to VEHdespawner, and cleared by the manual garbage collection.

**Comment by jaj22** [comment]
Found some code I missed. Both surrendered enemies and boxes are supposed to be removed by the function `A3A_fnc_postmortem` after `cleantime` has elapsed, which is set to an hour by default. Released enemies are removed after 100 seconds.

Seems to work correctly in testing. I'm guessing that the author returned a bit before the hour.

**Comment by Toakan** [comment]
Is anyone touching this one @jaj22? Else i'll self assign and start looking.

**Comment by Toakan** [comment]
From throwing the following in fn_surrenderAction

```SQF
// timed cleanup functions
unitStr = format["Cleanup called for unit:%1",_unit];
boxxStr = format["Cleanup called for boxx:%1",_boxX];
[3,unitStr,_filename] call A3A_fnc_log;
[_unit] spawn A3A_fnc_postmortem;

[3,boxXStr,_filename] call A3A_fnc_log;
[_boxX] spawn A3A_fnc_postmortem;

```

and this in fn_postmortem.sqf

```SQF

groupStr = format["Group for victim:%1 assigned:%2.",_victim, _group];
[3,unitStr,_filename] call A3A_fnc_log;
```

I received expected output when clearing down the boxes for two police after being triggered to surrender.

```
"1038.92: [Antistasi] | DEBUG | fn_surrenderAction | Cleanup called for unit:B Alpha 1-3:2"
"1038.92: [Antistasi] | DEBUG | fn_surrenderAction | Cleanup called for boxx:ee9dfa00# 1815953: wpnsbox_f.p3d"
"1038.94: [Antistasi] | DEBUG | fn_postmortem | Cleanup called for unit:B Alpha 1-3:2"
"1038.94: [Antistasi] | DEBUG | fn_postmortem | Cleanup called for unit:B Alpha 1-3:2"
```

Their current default timer is 3600 which is 1 hour, I think this could probably be shortened down or changed so that it's cleared when all players have left the immediate area rather than just laying around.

**Comment by jaj22** [comment]
The hour seems reasonable to me as a fixed timer. Too short if anything, as it's annoying when bodies start disappearing on you when you're looting after an extended battle. You can clear the bodies earlier with the garbage cleaner if necessary. Adding the surrender boxes to the garbage cleaner seems reasonable.

Spawner-proximity testing is a slow operation, so you may need to run it infrequently to gain any overall performance benefit. I think the main advantage would be not losing nearby bodies after the hour, rather than cleaning them up earlier. One option would be to continually reduce the cleanup distance over time.

From a performance perspective, there are a lot of unknowns. The scheduler thread itself may be a significant expense, although you'd hope not. The fact that many of these objects (corpses, dropped weapon holders, surrender boxes) remain simulated may be an easily-fixed issue, or it may be irrelevant.

**Comment by Toakan** [comment]
Created branch .589 which I'm working on now to find this, I believe it's being caused by the script effectively killing itself too early.

This needs further testing but is being looked at now.

**Comment by Toakan** [comment]
With a bit more logic tweak and debug tools you can now trace the generation of cleanup on any object, Box or Unit.

```
"1961.62: [Antistasi] | DEBUG | fn_surrenderAction | Cleanup called for boxx:d21a7e00# 1841857: wpnsbox_f.p3d"
"1961.66: [Antistasi] | DEBUG | fn_postmortem | PostMortem Called"
"1961.66: [Antistasi] | DEBUG | fn_postmortem | Group for victim :: d21a7e00# 1841857: wpnsbox_f.p3d, assigned :: <NULL-group>."
"1961.66: [Antistasi] | DEBUG | fn_postmortem | Pausing for 60 minutes before cleaning victim: d21a7e00# 1841857: wpnsbox_f.p3d and group: <NULL-group>"
"5570.27: [Antistasi] | DEBUG | fn_postmortem | Cleanup complete for d21a7e00# 1841857: wpnsbox_f.p3d victim."
```
