### ISSUE TITLE
Petros gear does not update during initialization.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#601]
Petros spawns first as vanilla and vulnerable. Upon killing him he wears the correct garments and becomes invincible.

**Comment by CalebSerafin** [comment]
Confirmed the issue is with Single-player fixes, but I'll set this as a low priority for myself as I believe it will iron itself out.

**Comment by Bob-Murphy** [comment]
That is because Petros is placed with vanilla gear within the mission.sqm.
Of course he at first gets spawned with this gear and then gets the correct one when properly loaded.
This is nothing special to your mod, it's the same with every modset.
The only way to prevent this would me going into the mission.sqm's and strip him completely.

**Comment by CalebSerafin** [comment]
I don't prefer that. But we could fix that in some sort of initialisation.:

The flagpole type
The flag texture
Petros Type

Because we have all the functions we need, they just need to be executed on him.

**Comment by Bob-Murphy** [comment]
We can't load everything on the same time, there are natural delays and some things are naturally loaded earlier than others. Spoffy already worked on it and honestly, it clearly has no priority to have Petros being pretty for the initial few seconds. The priority is a proper loading schedule which is benefitting the overall loading time.
With my change the only difference would be that Petros first would be completely naked for 5-10 seconds until he gets his gear and no vanilla gear would be visible at all.

**Comment by SonorousMeerkat** [comment]
But Petros DOESN'T change. unless this was fixed in 2.2.

**Comment by CalebSerafin** [comment]
Then there is an issue with current unstable, because Petros stays vanilla until you put a bullet through him, he respawns and becomes invincible

**Comment by Bob-Murphy** [comment]
Oh, then I misunderstood the problem.
Will convey it to Spoffy and open an issue for that.

**Comment by CalebSerafin** [comment]
Should I just make this an unstable issue?

**Comment by Bob-Murphy** [comment]
Could somebody please check if this is still an issue in 2.2 unstable?
Thank you in advance!

**Comment by rurku** [comment]
I'm playing current unstable Tembelan with RHS and can confirm that Petros begins with vanilla gear and stays that way until he gets killked and respawns. He was also like that when I played Chernarus Armia Krajowa (IFA).

**Comment by Bob-Murphy** [comment]
Thank you!

**Comment by jaj22** [comment]
Petros is dressed in createPetros, but that's only called when he dies or in placementSelection on map click. If you exit placementSelection without clicking (new game), or load a game, Petros is still the Petros from the SQM. 

As far as I can tell, createPetros should work fine on init. Also both createPetros and initPetros should be call rather than spawn, to prevent theoretical weird bugs like dying before his event handler kicks in.
