### ISSUE TITLE
TIOW-Antistasi Code garrisons outposts with vanilla patrols. The truck and static weapons at outposts conform to the modset.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#604]

**Comment by jaj22** [comment]
I'm not sure I understand. All garrisons use groupsNATOSquad, groupsCSATSquad and groupsFIASquad (the latter is occupant militia units, somewhat misnamed), plus staticCrewOccupants and staticCrewInvaders for the static crew. Outpost patrols use groupsNATOSmall, groupsFIASmall and groupsCSATSmall. I don't think there are any non-templated units.

Savegames store raw classnames for garrisons rather than abstracted types, so you can end up with garrison units from the wrong modset if you load a game, but I'm not sure if that's considered a bug. Personally I'd rather they were abstracted for forward compatibility.

**Comment by CalebSerafin** [comment]
Good catch, I was tired so I might of missed that.

**Comment by CalebSerafin** [comment]
Nope, confirmed the issue is with Single-player fixes, but I'll set this as a low priority for myself as I believe it will iron itself out. Watched the spawning up close, the RHS patrols get spawned, then disappear and Vanilla patrols get spawned.

**Comment by CalebSerafin** [comment]
I don't understand, maybe there was an issue listing different class names in certain parts of a template. But it fixed itself sometime after swapping out many Valhalla with Death Korps.
