### ISSUE TITLE
Consider a parameter save feature

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#650]
There are a lot of parameters to set right now, so it is annoying to set them every time. Consider some code to do that automatically.

**Comment by Bob-Murphy** [comment]
Liberation has such a system - see screenshots provided by eXCore
![image](https://user-images.githubusercontent.com/50651578/71820942-07f35480-3091-11ea-853a-17a6f7362946.png)
![image](https://user-images.githubusercontent.com/50651578/71820950-0e81cc00-3091-11ea-9eb8-ade211838591.png)

**Comment by Wyqer** [comment]
This might be helpful for you in this concern:
[Param fetching from lobby in Liberation](https://github.com/KillahPotatoes/KP-Liberation/blob/v.0.96.7/Missionframework/scripts/shared/fetch_params.sqf#L6-L113)
[Macros used in above](https://github.com/KillahPotatoes/KP-Liberation/blob/v.0.96.7/Missionframework/scripts/shared/defines.hpp)
[Actual load/save of param in profile namespace](https://github.com/KillahPotatoes/KP-Liberation/blob/v.0.96.7/Missionframework/functions/fn_getSaveableParam.sqf)

Feel free to state any questions, if there are any.

**Comment by Bob-Murphy** [comment]
Thank you for the input, Wyqer.

**Comment by jaj22** [comment]
Having a crack at this, doesn't look too complex. I'm not a big fan of the CO10 Escape/Liberation method though, because you can't change one parameter without remembering everything that you already changed (choice is either "load everything from save" or "use all the values below").

Trying a version instead where each parameter has a "Load (default)" value as well as overrides.
