### ISSUE TITLE
New bug - patrolCA

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#771]
`21:47:08 Error in expression <};
_timeOut = _timeOut + 1;
_pos = _pos findEmptyPosition [0,100,_typeVehX];
sle>
21:47:08   Error position: <findEmptyPosition [0,100,_typeVehX];
sle>
21:47:08   Error 0 elements provided, 3 expected
21:47:08 File functions\CREATE\fn_patrolCA.sqf [A3A_fnc_patrolCA]..., line 292`

RPT will be uploaded.

**Comment by jaj22** [comment]
This and #772 are probably caused by the empty arrays for vehNATOTransportPlanes and vehCSATTransportPlanes in the 3CB templates. Transport planes are a critical vehicle type and the mission won't work without them. Throw in something from RHS if there's nothing suitable in 3CB.

**Comment by SonorousMeerkat** [comment]
Can't be NATO as they are populated.
Even RHS Inv have _NO_ transport plane.

**Comment by SonorousMeerkat** [comment]
In this file, _typeVehX is never assigned a value, it just gets used.

**Comment by jaj22** [comment]
RHS Inv having no transport plane is probably a bug as well. But yeah, it's not the cause here.

`findEmptyPosition` on the attack origin is failing on ground units. I tested it on the areas that failed in the RPT, and it worked fine with real vehicle classnames. A one-character error in the classname causes the call to fail, so it looks like there is a bad classname, likely in APCs, tank or trucks. I can't check which one it is because I need to free up disk space for 3CB.

We should be sanity-checking the classnames on init, but given that the template structure is being reworked it's not worth doing now. Something to bear in mind for the template rework.
