### ISSUE TITLE
Include IFA civilian trucks in civilian vehicle type list

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#790]
Same problem like #781 but for IFA.
The buyable trucks don't go undercover.
Please fix. Thank you.

**Comment by jaj22** [comment]
Different problem from #781. IFA simply lacks civilian-faction vehicles (there's one staff car, basically), so the template uses greenfor vehicles instead. With the old hardcoded list it was possible to add specific greenfor vehicles as "civilian" so that they'd work with undercover, but if we're autodetecting then that's not an option.

I would strongly suggest switching civilian vehicles to weighted hardcoded lists anyway (which would also enable a much better fix for #781 and others), but that's your call.

**Comment by Bob-Murphy** [comment]
Indeed. It makes sense to do that.
As Spoffy (generally) said we should use the auto-detect stuff we have to create the basis of said lists and then hardcode them to have the ability to adjust.
You have my GO for it.
