### ISSUE TITLE
Move player spawn pos to the flag

### ISSUE THREAD

**Issue by doommetal** [official-antistasi-community/A3-Antistasi#838]
Petros often gets put inside a bunker which can lead to a traffic jam if a lot of people joing at the same time/are afk for a bit when joining etc, while the flag is usually in a more open spot.

**Comment by Bob-Murphy** [comment]
Approved

**Comment by jaj22** [comment]
It's actually the marker that's the spawn point, not Petros. Since the movable-Petros patch, the sensible option is to create your HQ in the open and then move Petros into a building.

Moving the spawn point means moving the HQ marker. As that has a lot of dependencies, it's liable to cause weird bugs and exploits. I don't think it's necessary anymore.

**Comment by Bob-Murphy** [comment]
I'll reassess the necessity of this one.

**Comment by killerswin2** [comment]
Not warranted anymore. Spawn pos is on the marker.
