### ISSUE TITLE
[Change Request]: Skill adjustments should recognize ACE

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#848]
Currently when the skill of AI is edited by the mission it only changes BI skill values. This makes ACE ridiculously more accurate because they stay at default (50%)

**Comment by SonorousMeerkat** [comment]
ACE AI wiki-page:
https://ace3mod.com/wiki/feature/ai.html

**Comment by jaj22** [comment]
I think you misunderstood what ACE is doing there. The Zeus module doesn't touch the AI skills until you actually create it. You can test with `cursorTarget skillFinal "general"`. It's essentially an optional override for mission skill, which is not a problem. The other ACE AI features don't touch accuracy.

My best guess is that AIs are far more accurate at range because there's a multiplicative dependence on base weapon dispersion, which ACE blats down to ~1 MOA for almost every weapon (see addons/ballistics/CfgWeapons.hpp). Each weapon also has aiDispersionCoefX and aiDispersionCoefY values, which are likely to be a multiple of the dispersion value, but these are left untouched so the result is much higher ranged accuracy. Evidence in favour of this theory is that if you strip out ACE ballistics and dependent modules, the AIs drop back to potato accuracy.

This could be fixed in a mod (which I am quite tempted to write), but not in Antistasi itself.

**Comment by Bob-Murphy** [comment]
I'll reassess the necessity of this one.

**Comment by jaj22** [comment]
ACE pulled the dispersion adjustments out of the main mod a while back.
