### ISSUE TITLE
TK warning hint not being triggered properly

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#862]
During some testing we have discovered that the warning hint for the shooter does not get triggered properly.
I don't know if the overhaul of the hints caused this to happen (#852) or something else.

**Comment by jaj22** [comment]
More likely #776. The TK warning was horribly bugged before too, especially since the ACE update, but the bugs were different. A known current issue is that it only triggers if the target is wearing a uniform from allCivilianUniforms or allRebelUniforms. The latter does not necessarily include all rebel uniforms.

Need more info anyway: Which modset, what you were shooting (AI vs player) and what they were wearing.

**Comment by Toakan** [comment]
This change means that unless you are wearing array specific gear, you can shoot and TK without repurcussion.

https://github.com/official-antistasi-community/A3-Antistasi/commit/6369b8f98c2dadc3fd909e199487cdf0dc561021

**Comment by jaj22** [comment]
It was already broken, but the cases were different. The previous check was that wearing any blufor or opfor uniform would dodge the TK check. This broke in two common cases:
1. The start-unlocked greenfor vanilla rebel uniforms are actually blufor.
2. If you play blufor, all rebels are wearing blufor uniforms.

There was a second TK check previously that didn't depend on the uniforms, but since the new ACE, only a one-shot kill would trigger it. This also broke the intention of not punishing TKs when players were wearing enemy uniforms, which some mods apparently permit.

The easy feature-complete fix is to use the greenfor guerrilla uniforms for greenfor. They have scope 1, but are still visible in the Antistasi arsenal as demonstrated above. I don't know if there are any introduced complications, but the last time I suggested this, it was denied for unclear reasons. Alternatively I can simply remove the side/uniform check.

IIRC PvP players get a free pass on punishment for being members, so TK checks don't need to work for them.

**Comment by Toakan** [comment]
Actually the easier option is to check what side they are on, and how much damage they do, which is what it did originally.

If you want to add a check to ignore certain uniforms, you could've placed an `exitwith` just before the damage check `remotexec punishment`.

All this does now is allow players to run around without a uniform selected and shoot each other.
