### ISSUE TITLE
Antistasi medic system revive time indicator

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#879]
As discussed in Dev Meeting on 21/03/2020 a time indicator for the medics with the antistasi heal system can be added.
Please note following restrictions for that feature:
- only a visual indicator for the time like the turning wheel, no exact time
- only visible for the medic, not for the person downed
- needs to have a paremeter to turn on/off

**Comment by Toakan** [comment]
I have lines on screens and a flashy display saying "REVIVING" now...

**Comment by Bob-Murphy** [comment]
Could you maybe upload a short clip?

**Comment by Toakan** [comment]
It may need to be put on hold, I think a proper refactor of the medical system would be overall better. The problem being that once you're in an animation loop there are too many `sleep` timers that it makes the counter incorrect.

**Comment by wurzel0701** [comment]
When this is done, it might be also applied to the intel search action

**Comment by Toakan** [comment]
The couple of times I wanted to make changes to `fn_actionRevive` it was pointed out that doing so would break mod compatibility with ACE due to some jank assumptions we have to make with it.

Ideallly the entirety of the first part of the file would be restructured to a SWITCH where it checks if the person carrying out the action is even capable. Lines  {9-60}

The timer on Lines {69-83} would be tweaked so it's just based on if you're a Medic, and if you have the tools available. If you're neither it takes x amount longer.

The event handlers are the bit that apparently breaks compat... Eugh.

I'm pretty sure that there is also some weird sleep jank left over at the bottom that can cause a user to get stuck in the prone position if a medic DC's whilst reviving someone and the script doesn't complete, but I haven't been able to pin down what was causing that.

@jaj22 should be able to clarify what ACE issues i'm on about in this, I think it was a discussion we had months back.

**Comment by Bob-Murphy** [comment]
Opening new issue for that one.
