### ISSUE TITLE
Remove custom flag ak.jpg

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#882]
We have the picture ak.jpg which is located in the folder of chernarus summer (and therefore is only available for said map) but is being called by the IFA_Reb_POL templates which can basically be used on every map.
We do not need a custom flagtexture which is based on an extra jpg file within the mission.
Please get rid of it and replace the flag-texture with something which is already part of the modset.

**Comment by Lazejun** [comment]
IFA only has 4 Flags:

![20200326232411_1](https://user-images.githubusercontent.com/57111907/77702512-fac37300-6fb8-11ea-807a-cbfb19a69eae.jpg)

Texturepaths:
"ww2\core_t\if_decals_t\german\flag_ger_co.paa"
"ww2\core_t\if_decals_t\us\flag_usa_co.paa"
"a3\data_f\flags\flag_uk_co.paa"
"ww2\core_t\if_decals_t\ussr\flag_su_co.paa"

Classnames:
LIB_FlagCarrier_GER
LIB_FlagCarrier_USA
LIB_FlagCarrier_UK
LIB_FlagCarrier_SU

Due to IFA having CUP dependencies:
there is also what Cup Terrain Core has to offer which are:
![20200326233539_1](https://user-images.githubusercontent.com/57111907/77703206-88ec2900-6fba-11ea-8ea7-6745e1c5a0fe.jpg)

Texuture Path:
White Flag: "ca\ca_e\data\flag_white_co.paa"
Czech Flag: "ca\ca_e\data\flag_cz_co.paa"

Classname:
FlagCarrierWhite_EP1
FlagCarrierCzechRepublic_EP1

------------> Fuck it, Altis Flag
Flag_Altis_F
"a3\data_f\flags\flag_altis_co.paa"
