### ISSUE TITLE
Error in JN_fnc_logistics_getCargoOffsetAndDir

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#910]
Error was sighted within a rpt of a standard RPT.

RPT available here: https://drive.google.com/open?id=1CcRqOfgch06d8KUpVmWDEkkeSnGUKcjM

Error
```
17:06:14 Error in expression <entOffset;
};
_objectOffset = _nodePos vectoradd _objectOffset;
[_objectOffse>
17:06:14   Error position: <vectoradd _objectOffset;
[_objectOffse>
17:06:14   Error vectoradd: Type Number, expected Array
17:06:14 File JeroenArsenal\JNL\Functions\fn_logistics_getCargoOffsetAndDir.sqf [JN_fnc_logistics_getCargoOffsetAndDir]..., line 43```

**Comment by jaj22** [comment]
It looks like this is caused by attempting to cargo-load an object that isn't defined in JNL's attachmentOffset list. Beyond that, I don't know how it's possible: As far as I know, Antistasi only adds the JNL load action to unconscious people and the NATO/CSAT cargo crates. 3CB was running at the time but I don't think that changes anything relevant.

**Comment by jaj22** [comment]
Oh, it's probably the surrender crates. I had no idea those had a JNL load action added.

Need to decide whether to make the surrender crates loadable, or just remove the logistics action from them.
