### ISSUE TITLE
Tent retains velocity on placement

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#963]
*Version:* Unstable

*Mods:* None

*Environment*: MP Dedi

*.rpt attatched?* No

*have you edited the missionfile?*: ~~

***Issue:***
When setting up a base camp, the Tent retains its velocity from placement. Be that the Spawn in placement or Player placement.

![image](https://user-images.githubusercontent.com/7566941/79791045-917b1980-8344-11ea-841c-26d95c5ccc66.png)

![image](https://user-images.githubusercontent.com/7566941/79791011-888a4800-8344-11ea-876b-c8314a82a4ea.png)

**Comment by jaj22** [comment]
So as far as I can tell, it's difficult to completely prevent tent-deaths on a DS. Even zeroing the player and tent velocity before the drop, and again after the drop (with remoteExec, because it's no longer local), running forward while dropping the thing will still kill you. Arma networking is weird.

Best bet is probably to space the object attachment a bit more with the bounding box, and remoteExec the velocity to zero after the drop. Should only kill idiots that way, at least.
