### ISSUE TITLE
AIVEHinit is called for rebel vehicles

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#980]
AIVEHinit should be only used for enemy AI vehicles as killing these vehicles increases aggro, city support and some other stuff. It needs either a block which keep the eventhandler from firing when the vehicle is in rebel hand, or a complete seperate init file for rebel vehicles.

It is linked to a problem in #975

**Comment by jaj22** [comment]
Related problems:
- Enemy vehicle pool not being reduced when a vehicle is captured.
- Marker vehicle despawners relying on some brain-damaged distance calculation rather than deactivating when a vehicle is stolen.

I think a half-decent system would be to store an ownership parameter on spawned vehicles, and use the GetIn event handler (which seems to trigger regardless of locality) to mark the vehicle as stolen (or remove the ownership parameter) when a rebel enters it. Can do vehicle pool reduction and aggro adjustments at the same time.

Other related horror: A lot of these Killed EHs fail to fire in practice because Killed only fires on local objects, and vehicles switch locality when players enter them. For example if you capture a Bradley, get out and then blow it up, the EH won't fire. Similarly if one player spawns the vehicle from the faction garage and another player does the driving.
