### ISSUE TITLE
"Load previous save" is misleading.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#990]
The dialogue present on server joining for loading your personal stats and loadout is written in a way that can, and has, mislead hosts as to its function. This dialogue should be clarified as it has caused a workshop user to delete their save when they had another issue with trying to load a savegame.

**Comment by jaj22** [comment]
Wondered why this exists at all. I'd rather hand out some pocket money than have people reset their player data because they want their $100 back.

Not sure how it'd be misunderstood though. If you thought it was going to reset the entire game, then it's not going to cause any additional pain beyond having to work out how to start a new game on an autoinit DS. Worst case is probably a misclick.
